language: go

before_install:
  - sudo apt-get install gfortran

install:
  - go get github.com/ready-steady/support/assert
  - (cd lapack && make install)
  - go build -v ./...
  - go test -v ./...

notifications:
  email:
    on_success: never
