language: go

before_install:
  - sudo apt-get install gfortran

install:
  - go get -t ./...
  - git submodule update --init
  - (cd lapack && make install)
  - go build -v ./...

notifications:
  email:
    on_success: never
