language: go

before_install:
  - sudo apt-get install gfortran

install:
  - go get -d -t ./...
  - (cd /home/travis/gopath/src/github.com/ready-steady/lapack && git submodule update --init && make install)
  - go test -v ./...

notifications:
  email:
    on_success: never
